### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by selma-belhadj**
Pull request by user @selma-belhadj
What does this PR do?
Designing Template of Leaderboard setup project by:
-  Create an npm project with webpack
-  Write plain HTML markup

How should it be tested?
By running npm test in the terminal.

clone the repository
`git clone git@github.com:selma-belhadj/leaderboard-setup.git
`
navigate to the folder
`cd leaderboard-setup
`
checkout the feature
`git checkout feature`

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hi @selma-belhadj,

Great Job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
### To highlight
1. The project has an HTML file for the use to interact with the page.

## Required Changes ♻️
_Check the comments under the review._
- Since the other important files were committed in a different branch, I'm unable to review them. However, I suggest that the readme file contain instructions on how to run the project on a users local machine.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Though tests are not yet written, running npm test will not work, this is because the test command in the package.json script doesn't contain a proper test command. 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by selma-belhadj** [comment]
Hello @elisha2kyakpo1, thank you for review ... I wonder what are the other important files that were committed in a different branch, and you are unable to review them? every required file is in the branch of `feature`. Could you please clarify more?

**Comment by elisha2kyakpo1** [comment]
Hi, @selma-belhadj thanks for contacting me. I was expecting to see webpack configuring and package.json files in the files changed, but do not worry because I checked then and they are fine. This is the reason I only requested the readme file update. Let me know if there is anything you do not understand about my review

**Review by mikethreels — APPROVED** [review]
Hi Selma, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
